language: go

matrix:
  include:
    - go: 1.x
    - go: 1.13.x
    - go: 1.12.x
    - go: 1.11.x
    - go: 1.10.x
    - go: 1.9.x
    - go: tip
  allow_failures:
    - go: tip

env:
  global:
    - DEP_VERSION="0.5.4"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64
    -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure -v

script:
  - go test -v -race ./...
